name: Contracts

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  contracts_run_ts_tests:
    name: Run Typescript Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Install Nix
        uses: cachix/install-nix-action@29bd9290ef037a3ecbdafe83cbd2185e9dd0fa0a # v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Cairo
        uses: ./.github/actions/install-cairo

      - name: Test
        run: nix develop -c make test-ts-contracts

  contracts_run_cairo_tests:
    name: Run Cairo Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          submodules: 'recursive'

      - name: Install Nix
        uses: cachix/install-nix-action@5c11eae19dba042788936d4f1c9685fdd814ac49 # v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Cairo
        uses: ./.github/actions/install-cairo

      - name: Test
        run: nix develop -c make test-cairo-contracts

  contracts_build:
    name: Build contracts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          submodules: 'recursive'

      - name: Install Nix
        uses: cachix/install-nix-action@5c11eae19dba042788936d4f1c9685fdd814ac49 # v19
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Cairo
        uses: ./.github/actions/install-cairo

      - name: Build
        run: nix develop -c make build-contracts

      - name: Generate & Push
        run: |
            date > generated.txt
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add generated.txt
            git commit -m "generated"
            git tag test-tag
            git push origin test-tag
